linters:
  enable:
    - errcheck        # checks for unchecked errors in go programs
    - errname         # checks that sentinel errors are prefixed with the `Err` and error types are suffixed with the `Error`
    - exportloopref   # checks for pointers to enclosing loop variables
    - gosimple        # simplifies code
    - govet           # checks for suspicious constructs
    - importas        # enforces consistent import aliases
    - ineffassign     # detects when assignments to existing variables are not used
    - mirror          # reports wrong mirror patterns of bytes/strings usage
    - misspell        # Finds commonly misspelled English words in comments
    - nestif          # Reports deeply nested if statements
    - prealloc        # finds slice declarations that could potentially be preallocated
    - staticcheck     # some rules from the staticcheck binary
    - stylecheck      # Stylecheck is a replacement for golint
    - tenv            # detects using os.Setenv instead of t.Setenv
    - thelper         # detects golang test helpers without t.Helper() call and checks consistency of test helpers
    - unconvert       # removes unnecessary type conversions
    - unparam         # removes unused function parameters
  fast: true
